server.port=8081

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

security.jwt.secret=${SECURITY_JWT_SECRET:change-me-please-change-me-please-change-me-2026}
security.jwt.expiration-seconds=1800

