server.port=8082

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

security.jwt.secret=${SECURITY_JWT_SECRET:change-me-please-change-me-please-change-me-2026}

